### ISSUE TITLE
Adding gem leads to error

### ISSUE THREAD

**Issue by andersennl** [tkadauke/motion-i18n#13]
Hi, as the docs suggest, I've added the gem to my gemfile (this is the only thing I did). When I rake, I get the following error. Did I miss something? Thanks!

``` ruby
rake aborted!
NoMethodError: undefined method `each' for nil:NilClass
/Users/nandersen/Documents/RubyMotion/lactase2/vendor/bundle/gems/motion-i18n-0.0.6/lib/motion-i18n-ios/translate.rb:25:in `block (2 levels) in ios_translate'
/Users/nandersen/Documents/RubyMotion/lactase2/vendor/bundle/gems/motion-i18n-0.0.6/lib/motion-i18n-ios/translate.rb:24:in `open'
/Users/nandersen/Documents/RubyMotion/lactase2/vendor/bundle/gems/motion-i18n-0.0.6/lib/motion-i18n-ios/translate.rb:24:in `block in ios_translate'
/Users/nandersen/Documents/RubyMotion/lactase2/vendor/bundle/gems/motion-i18n-0.0.6/lib/motion-i18n-ios/translate.rb:19:in `each'
/Users/nandersen/Documents/RubyMotion/lactase2/vendor/bundle/gems/motion-i18n-0.0.6/lib/motion-i18n-ios/translate.rb:19:in `ios_translate'
/Users/nandersen/Documents/RubyMotion/lactase2/vendor/bundle/gems/motion-i18n-0.0.6/lib/motion-i18n-ios/translate.rb:34:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/ios.rb:186:in `block in <top (required)>'
```

**Comment by buffpojken** [comment]
@andersennl That's most probably due to the locale-file not following the Ruby i18n-standard, do you have the locale key on top of the YAML-file like this? 

```
en:
  holding:
    title: "Snart börjar Demokrativerkstaden3."
```

**Comment by andersennl** [comment]
Ah I see, that was probably it. I can't verify that at the moment but hanks for the response, though.
